{{- if .Copyright -}} // {{.Copyright}}

{{ end -}}
// Code generated by check-gen; DO NOT EDIT.
// Package {{.Package}} contains models and autogenerated validation code
package {{.Package}}
{{if or .StandardImports .CustomImports}}
import (
{{- if .StandardImports -}}
{{- range .StandardImports }}
	"{{- . -}}"
{{- end -}}
{{- end -}}
{{ if .CustomImports }}
{{- if .StandardImports }}
{{ end -}}
{{- range .CustomImports }}
	"{{- . -}}"
{{- end -}}
{{- end }}
)
{{end -}}
{{.Body -}}